// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ICreateOsRelease is an autogenerated mock type for the ICreateOsRelease type
type ICreateOsRelease struct {
	mock.Mock
}

// CreateOsRelease provides a mock function with given fields:
func (_m *ICreateOsRelease) CreateOsRelease() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateOsRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICreateOsRelease creates a new instance of ICreateOsRelease. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateOsRelease(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateOsRelease {
	mock := &ICreateOsRelease{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
