// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUpdateCMServer is an autogenerated mock type for the IUpdateCMServer type
type IUpdateCMServer struct {
	mock.Mock
}

// UpdateCMServer provides a mock function with given fields:
func (_m *IUpdateCMServer) UpdateCMServer() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUpdateCMServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUpdateCMServer creates a new instance of IUpdateCMServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUpdateCMServer(t mockConstructorTestingTNewIUpdateCMServer) *IUpdateCMServer {
	mock := &IUpdateCMServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
