// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ICreateAutoyastProfile is an autogenerated mock type for the ICreateAutoyastProfile type
type ICreateAutoyastProfile struct {
	mock.Mock
}

// CreateAutoyastProfile provides a mock function with given fields:
func (_m *ICreateAutoyastProfile) CreateAutoyastProfile() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewICreateAutoyastProfile interface {
	mock.TestingT
	Cleanup(func())
}

// NewICreateAutoyastProfile creates a new instance of ICreateAutoyastProfile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICreateAutoyastProfile(t mockConstructorTestingTNewICreateAutoyastProfile) *ICreateAutoyastProfile {
	mock := &ICreateAutoyastProfile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
