// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUpdateRoutes is an autogenerated mock type for the IUpdateRoutes type
type IUpdateRoutes struct {
	mock.Mock
}

// UpdateRoutes provides a mock function with given fields:
func (_m *IUpdateRoutes) UpdateRoutes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUpdateRoutes interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUpdateRoutes creates a new instance of IUpdateRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUpdateRoutes(t mockConstructorTestingTNewIUpdateRoutes) *IUpdateRoutes {
	mock := &IUpdateRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
